version: '3.8'

networks:
  backend:
    name: sam-user-api

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.12.12
    networks:
      - backend
    ports:
      - '127.0.0.1:53:53'
      - '127.0.0.1:53:53/udp'
      - '127.0.0.1:443:443'
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4571:4571'
    environment:
      # - SERVICES=${SERVICES- }
      - SERVICES=dynamodb,lambda
      - DEFAULT_REGION=us-east-1
      # - DEBUG=${DEBUG- }
      - DEBUG=1
      # - DATA_DIR=${DATA_DIR- }
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
