AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  users-microservice

  Sample SAM Template for users-microservice

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        TABLE_NAME: !Ref TableName
        DEPLOY_ENVIRONMENT: !Ref DeployEnviroment
        #AWS_REGION: !Ref AWSRegion
        IS_OFFLINE: !Ref IsOffline #change this to false for deploy in aws or true for use in offline
        DYNAMOHOST: !Ref DynamoHost
        DYNAMO_PORT: 4566
        SECRET_KEY: !Ref SecretKey
        EXPIRATION: !Ref Expiration

Parameters:
  TableName:
    Type: String
  DeployEnviroment:
    Type: String
  IsOffline:
    Type: String
  DynamoHost:
    Type: String
  SecretKey:
    Type: String
  Expiration:
    Type: String

Resources:
  TopicUserService:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: TopicUserService 
      TopicName: TopicUserService
      KmsMasterKeyId: alias/aws/sns
      DeliveryPolicy:
        HTTP:
          defaultHealthyRetryPolicy:
            minDelayTarget: 20
            maxDelayTarget: 20
            numRetries: 3
            numMaxDelayRetries: 0
            numNoDelayRetries: 0
            backoffFunction: linear
          disableSubscriptionOverrides: false
          defaultThrottlePolicy:
            maxReceivesPerSecond: 1
          disableSubscriptionOverrides: false
        HTTPS:
          defaultHealthyRetryPolicy:
            minDelayTarget: 20
            maxDelayTarget: 20
            numRetries: 3
            numMaxDelayRetries: 0
            numNoDelayRetries: 0
            backoffFunction: linear
          disableSubscriptionOverrides: false
          defaultThrottlePolicy:
            maxReceivesPerSecond: 1
          disableSubscriptionOverrides: false
      Tags:
        - Key: Environment
          Value: Production
  UserQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: UserQueue
      VisibilityTimeout: 300 
      MaximumMessageSize: 2048 
      MessageRetentionPeriod: 86400 
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt UserDeadLetterQueue.Arn 
        maxReceiveCount: 5
      Tags:
        - Key: Environment
          Value: Production
  UserDeadLetterQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: UserDeadLetterQueue 
      MessageRetentionPeriod: 1209600
  MySQSToSNSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: 'sqs'
      TopicArn: !Ref TopicUserService
      Endpoint: !GetAtt UserQueue.Arn
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        # Defining table attributes
        - AttributeName: id
          AttributeType: S
        - AttributeName: username
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        # Primary Key Definition
        - AttributeName: id
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: UsernameIndex
          KeySchema:
            # Secondary Global Index Key Definition
            - AttributeName: username
              KeyType: HASH
          Projection:
            # Specifies which attributes should be projected to the index
            ProjectionType: ALL
        - IndexName: EmailIndex
          KeySchema:
            # Secondary Global Index Key Definition
            - AttributeName: email
              KeyType: HASH
          Projection:
            # Specifies which attributes should be projected to the index
            ProjectionType: ALL

  CreateUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/
      Handler: create-user.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Architectures:
        - x86_64
      Events:
        UserAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - create-user.ts

  GetUserById:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/
      Handler: get-user-by-id.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Architectures:
        - x86_64
      Events:
        UserAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get/{userId}
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - get-user-by-id.ts

  GetUsers:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/
      Handler: get-users.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Architectures:
        - x86_64
      Events:
        UserAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - get-users.ts

  DeleteUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/
      Handler: delete-user.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Architectures:
        - x86_64
      Events:
        UserAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /delete/{userId}
            Method: delete
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - delete-user.ts

  UpdateUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/
      Handler: update-user.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Architectures:
        - x86_64
      Events:
        UserAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /update/{userId}
            Method: patch
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - update-user.ts

  LoginUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/
      Handler: login.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicUserService
      Architectures:
        - x86_64
      Environment:
        Variables:
          TOPIC_ARN: !Ref TopicUserService
      Events:
        UserAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /login
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - login.ts

  NotificationUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/
      Handler: notification.handler
      Runtime: nodejs18.x
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt UserQueue.QueueName
      Architectures:
        - x86_64
      Events:
        UserQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt UserQueue.Arn
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - login.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateUser:
    Description: API Gateway endpoint URL for Prod stage for CreateUser function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create/'
