export enum DomainErrorCode {
  DTO_PROPERTIES_ERROR = 'DTO_PROPERTIES_ERROR',
  INVALID_PROPERTY = 'INVALID_PROPERTY',
  BODY_ERROR = 'BODY_ERROR',
  ID_PATH_PARAMETER_MISSING = 'ID_PATH_PARAMETER_MISSING',
  USER_NOT_FOUND = 'USER_NOT_FOUND'
}
