name: CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Lint & Test
    runs-on: ubuntu-latest
    container: node:lts
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: FN Eslint
        run: cd functions && yarn lint
      - name: Layers Eslint
        run: cd layers && yarn lint
      - name: FN Compilation
        run: cd functions && yarn compile
      - name: Layers Compilation
        run: cd layers && yarn compile
      - name: Building
        run: yarn build
      # - name: Tests
      #   run: yarn test
