name: CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Lint & Test
    runs-on: ubuntu-latest
    container: node:lts
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Verify secrets
        run: echo ${{ secrets.AWS_REGION }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: FN Eslint
        run: cd lambdas && yarn && yarn lint
      - name: Layers Eslint
        run: cd layers/general && yarn && yarn lint
      - name: Layers Compilation
        run: cd layers/general && yarn build
      - name: Building
        run: yarn build
      # - name: Tests
      #   run: yarn test
