name: CI

on:
  pull_request:
    branches:
      - main
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  skip-draft:
    name: skip draft
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: fail on draft
        if: github.event.pull_request.draft == true
        run: echo "is a draft PR, failing..." && exit 1
      - name: success
        run: echo "is not a draft PR"

  tests:
    needs: skip-draft
    name: Lint & Test
    runs-on: ubuntu-latest
    container: node:lts
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Verify secrets
        run: echo ${{ secrets.AWS_REGION }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: FN Eslint
        run: cd lambdas && yarn lint
      - name: Layers Eslint
        run: cd layers && yarn lint
      - name: FN Compilation
        run: cd lambdas && yarn compile
      - name: Layers Compilation
        run: cd layers && yarn build
      - name: Building
        run: yarn build
      # - name: Tests
      #   run: yarn test
